sudo: require
services:
 - docker

before_install:
  - docker build -t wilcokuyper/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run wilcokuyper/react-test npm run test -- --coverage

after_success:
  - docker build -t wilcokuyper/multi-client ./client
  - docker build -t wilcokuyper/multi-server ./server
  - docker build -t wilcokuyper/multi-worker ./worker
  - docker build -t wilcokuyper/multi-nginx ./nginx
# login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wilcokuyper/multi-client
  - docker push wilcokuyper/multi-server
  - docker push wilcokuyper/multi-worker
  - docker push wilcokuyper/multi-nginx